### ISSUE TITLE
ImportError: No module named scripts.bitbucket

### ISSUE THREAD

**Issue by bananphone12** [unk1nd0n3/bitbucket-creds-checker#2]
Traceback (most recent call last):
  File "bitchecker.py", line 22, in <module>
    from scripts.bitbucket import Bitbucket
ImportError: No module named scripts.bitbucket

**Comment by unk1nd0n3** [comment]
Hi, 
you need to run script from cloned repo. Class Bitbucket is located in path of cloned repo: cloned_repo/scripts/bitbucket.py

**Comment by saurabhvashisht** [comment]
Is it possible to run the script manually on the local bitbucket repositories NAS.

**Comment by unk1nd0n3** [comment]
Yes, with not_clone option. But repos must be cloned into folder of repo: **repos**.

There need to improve script and add possibility to set path to folder with repos

**Comment by unk1nd0n3** [comment]
Resolution was provided
